stages:
  - test
  - build
  - release
  - deploy

job_test:
  stage: test
  image: python:3.6-jessie
  variables:
    GOPATH: $HOME
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  cache:
    paths:
    - .cache/pip
    - venv/
  before_script:
  - ls -l
  - pwd
  - mkdir -p $GOPATH/src/github.com/elastos/Elastos.ELA
  - cd $GOPATH/src/github.com/elastos/Elastos.ELA
  - ls -l
  - pwd
  - wget http://172.16.0.120/ela
  - wget http://172.16.0.120/ela-cli
#  - export http_proxy=http://221.220.136.163:13128
#  - export https_proxy=$http_proxy

  script:
    - cd /builds/${CI_PROJECT_PATH}
    - ls -l
    - pwd
    - python -V
    - python -m pip install -r requirements.txt
    - python dpos_normal_test.py
    - echo Something in the test step in a python:3 image
    - echo case1

