stages:
  - test
  - build
  - release
  - deploy

job_test:
  stage: test
  image: python:3.6-jessie
  variables:
    GOPATH: "$HOME/dev"
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

  cache:
    paths:
    - .cache/pip

  before_script:
  - mkdir -p $GOPATH/src/github.com/elastos/Elastos.ELA
  - cd $GOPATH/src/github.com/elastos/Elastos.ELA
  - wget http://172.16.0.120/ela
  - wget http://172.16.0.120/ela-cli
  - chmod +x *c

  script:
    - cd /builds/${CI_PROJECT_PATH}
    - python -V
    - python -m pip install -r requirements.txt
    - python dpos_normal_test.py

