#!/usr/bin/env python
# encoding: utf-8

# author: liteng
# contact: liteng0313@gmail.com
# time: 2019-01-16 17:29
# file: constant.py


JAR_NAME = "Elastos.ELA.AutoTest.Java.jar"
JAR_ELA_TOOL = "ela_tool.jar"
JAR_ELA_OLD = "old.jar"
JAR_NEW_NAME = "Elastos.ELA.AutoTest.New.Java.jar"
JAR_HTTP_SERVICE = " org.elastos.elaweb.HttpServer"

NODE_BINARY_MAIN = "ela"
NODE_BINARY_ARBITER = "arbiter"
NODE_BINARY_DID = "did"
NODE_BINARY_TOKEN = "token"
NODE_BINARY_NEO = "neo"

CONFIG_TITLE = "Configuration"

CONFIG_MAGIC = "Magic"
CONFIG_SPV_MAGIC = "SpvMagic"
CONFIG_MAGIC_ELA = 20190131
CONFIG_MAGIC_ARBITER = 20190228
CONFIG_MAGIC_DID = 20190331
CONFIG_MAGIC_TOKEN = 20190430
CONFIG_MAGIC_NEO = 20190531

CONFIG_SEED_LIST = "SeedList"
CONFIG_PP_LIST = "PermanentPeers"
CONFIG_SPV_SEED_LIST = "SpvSeedList"

CONFIG_MAIN_CHAIN_FOUNDATION_ADDRESS = "MainChainFoundationAddress"
CONFIG_FOUNDATION_ADDRESS = "FoundationAddress"

CONFIG_PORT_NODE = "NodePort"
CONFIG_PORT_INFO = "HttpInfoPort"
CONFIG_PORT_REST = "HttpRestPort"
CONFIG_PORT_WS = "HttpWsPort"
CONFIG_PORT_JSON = "HttpJsonPort"
CONFIG_PORT_OPEN = "NodeOpenPort"
CONFIG_PORT_MAIN_CHAIN_DEFAULT = "MainChainDefaultPort"
CONFIG_PORT_ARBITER_MAIN_DEFAULT = "DefaultPort"

CONFIG_PRINT_LEVEL = "PrintLevel"

CONFIG_PAY_TO_ADDR = "PayToAddr"
CONFIG_AUTO_MINING = "AutoMining"
CONFIG_INSTANT_BLOCK = "InstantBlock"
CONFIG_POW = "PowConfiguration"
CONFIG_POW_CHAIN = "PowChain"
CONFIG_ARBITER_ENABLE = "EnableArbiter"
CONFIG_ORIGIN_ARBITERS = "OriginArbiters"

CONFIG_ARBITER_CONFIGURATION = "ArbiterConfiguration"
CONFIG_PUBLIC_KEY = "PublicKey"
CONFIG_CRC_ARBITERS = "CRCArbiters"
CONFIG_NET_ADDRESS = "NetAddress"
CONFIG_IP_ADDRESS = "IPAddress"
CONFIG_NORMAL_ARBITERS_COUNT = "NormalArbitratorsCount"
CONFIG_CANDIDATES_COUNT = "CandidatesCount"
CONFIG_PRE_CONNECT_OFFSET = "PreConnectOffset"
CONFIG_CHECK_ADDRESS_HEIGHT = "CheckAddressHeight"
CONFIG_VOTE_START_HEIGHT = "VoteStartHeight"
CONFIG_ONLY_DPOS_HEIGHT = "CRCOnlyDPOSHeight"
CONFIG_PUBLIC_DPOS_HEIGHT = "PublicDPOSHeight"

CONFIG_RPC = "RpcConfiguration"
CONFIG_RPC_USER = "User"
CONFIG_RPC_PASS = "Pass"
CONFIG_RPC_WHITE_LIST = "WhiteIPList"

CONFIG_ARBITER_MAIN_NODE = "MainNode"
CONFIG_ARBITER_RPC = "Rpc"
CONFIG_ARBITER_IP_ADDRESS = "IpAddress"
CONFIG_MIN_OUTBOUND = "MinOutbound"
CONFIG_MAX_CONNECTION = "MaxConnections"
CONFIG_MAX_INACTIVATE_ROUNDS = "MaxInactiveRounds"
CONFIG_EXCHANGE_RATE = "ExchangeRate"
CONFIG_GENESIS_BLOCK = "GenesisBlock"
CONFIG_MINER_ADDRESS = "MiningAddr"
CONFIG_SIDE_NODE_LIST = "SideNodeList"

CONFIG_ORIGIN_CROSS_CHAIN_ARBITERS = "OriginCrossChainArbiters"
CONFIG_CRC_CROSS_CHAIN_ARBITERS = "CRCCrossChainArbiters"
CONFIG_CRC_ONLY_DPOS_HEIGHT = "CRCOnlyDPOSHeight"




PROJECT_NAME = "Elastos.ELA.TestFramework"

TO_SELA = 100000000



