#!/usr/bin/env python
# encoding: utf-8

# author: liteng
# contact: liteng0313@gmail.com
# time: 2019-01-16 17:29
# file: constant.py


JAR_NAME = "Elastos.ELA.AutoTest.Java.jar"
JAR_ELA_TOOL = "ela_tool.jar"
JAR_ELA_OLD = "old.jar"
JAR_NEW_NAME = "Elastos.ELA.AutoTest.New.Java.jar"
JAR_HTTP_SERVICE = " org.elastos.elaweb.HttpServer"

NODE_BINARY_MAIN = "ela"
NODE_BINARY_ARBITER = "arbiter"
NODE_BINARY_DID = "did"
NODE_BINARY_TOKEN = "token"
NODE_BINARY_NEO = "neo"

CONFIG_TITLE = "Configuration"
CONFIG_ACTIVE_NET = "ActiveNet"
CONFIG_MAGIC = "Magic"
CONFIG_SPV_MAGIC = "SPVMagic"

CONFIG_MAGIC_DPOS = 2019200
CONFIG_MAGIC_ELA = 2018201
CONFIG_MAGIC_ARBITER = 2018203
CONFIG_MAGIC_DID = 2018202
CONFIG_MAGIC_TOKEN = 2019204
CONFIG_MAGIC_NEO = 2019205

CONFIG_SEED_LIST = "SeedList"
CONFIG_PERMANENT_PEERS = "PermanentPeers"
CONFIG_SPV_SEED_LIST = "SpvSeedList"

CONFIG_MAIN_CHAIN_FOUNDATION_ADDRESS = "MainChainFoundationAddress"
CONFIG_FOUNDATION_ADDRESS = "FoundationAddress"

CONFIG_PORT_NODE = "NodePort"
CONFIG_PORT_INFO = "HttpInfoPort"
CONFIG_PORT_REST = "HttpRestPort"
CONFIG_PORT_WS = "HttpWsPort"
CONFIG_PORT_JSON = "HttpJsonPort"
CONFIG_PORT_OPEN = "NodeOpenPort"
CONFIG_PORT_DPOS = "DPoSPort"
CONFIG_PORT_MAIN_CHAIN_DEFAULT = "MainChainDefaultPort"
CONFIG_PORT_ARBITER_MAIN_DEFAULT = "DefaultPort"

CONFIG_PRINT_LEVEL = "PrintLevel"

CONFIG_PAY_TO_ADDR = "PayToAddr"
CONFIG_AUTO_MINING = "AutoMining"
CONFIG_INSTANT_BLOCK = "InstantBlock"
CONFIG_POW = "PowConfiguration"
CONFIG_POW_CHAIN = "PowChain"
CONFIG_ARBITER_ENABLE = "EnableArbiter"
CONFIG_ORIGIN_ARBITERS = "OriginArbiters"

CONFIG_ARBITER_CONFIGURATION = "DPoSConfiguration"
CONFIG_PUBLIC_KEY = "PublicKey"
CONFIG_CRC_ARBITERS = "CRCArbiters"
CONFIG_NET_ADDRESS = "NetAddress"
CONFIG_IP_ADDRESS = "IPAddress"
CONFIG_NORMAL_ARBITERS_COUNT = "NormalArbitratorsCount"
CONFIG_CANDIDATES_COUNT = "CandidatesCount"
CONFIG_PRE_CONNECT_OFFSET = "PreConnectOffset"
CONFIG_CHECK_ADDRESS_HEIGHT = "CheckAddressHeight"
CONFIG_VOTE_START_HEIGHT = "VoteStartHeight"
CONFIG_ONLY_DPOS_HEIGHT = "CRCOnlyDPOSHeight"
CONFIG_PUBLIC_DPOS_HEIGHT = "PublicDPOSHeight"

CONFIG_RPC = "RpcConfiguration"
CONFIG_RPC_USER = "User"
CONFIG_RPC_PASS = "Pass"
CONFIG_RPC_WHITE_LIST = "WhiteIPList"

CONFIG_NET_TYPE = "regtest"

CONFIG_ARBITER_MAIN_NODE = "MainNode"
CONFIG_ARBITER_RPC = "Rpc"
CONFIG_ARBITER_IP_ADDRESS = "IpAddress"
CONFIG_MIN_OUTBOUND = "MinOutbound"
CONFIG_MAX_CONNECTION = "MaxConnections"
CONFIG_MAX_INACTIVATE_ROUNDS = "MaxInactiveRounds"
CONFIG_EXCHANGE_RATE = "ExchangeRate"
CONFIG_GENESIS_BLOCK = "GenesisBlock"
CONFIG_MINER_ADDRESS = "MiningAddr"
CONFIG_SIDE_NODE_LIST = "SideNodeList"
CONFIG_DPOS_NET_ADDRESS = "DPoSNetAddress"
CONFIG_SPV_PRINT_LEVEL = "SpvPrintLevel"
CONFIG_ORIGIN_CROSS_CHAIN_ARBITERS = "OriginCrossChainArbiters"
CONFIG_CRC_CROSS_CHAIN_ARBITERS = "CRCCrossChainArbiters"
CONFIG_CRC_ONLY_DPOS_HEIGHT = "CRCOnlyDPOSHeight"

CONFIG_SIDE_ENABLE_RPC = "EnableRPC"
CONFIG_SIDE_ENABLE_REST = "EnableREST"
CONFIG_SIDE_ENABLE_WS = "EnableWS"

CONFIG_SIDE_PORT_REST = "RESTPort"
CONFIG_SIDE_PORT_WS = "WSPort"
CONFIG_SIDE_PORT_RPC = "RPCPort"

CONFIG_SIDE_RPC_USER = "RPCUser"
CONFIG_SIDE_RPC_PASS = "RPCPass"
CONFIG_SIDE_RPC_WHITE_LIST = "RPCWhiteList"
CONFIG_SIDE_LOG_LEVEL = "Loglevel"

CONFIG_DISABLE_DNS = "DisableDNS"
CONFIG_SIDE_SPV_DISABLE_DNS = "SPVDisableDNS"
CONFIG_SIDE_SPV_PERMANENT_PEERS = "SPVPermanentPeers"
CONFIG_SIDE_ENABLE_MINING = "EnableMining"

CONFIG_INACTIVE_PENALTY = "InactivePenalty"
CONFIG_EMERGENCY_INACTIVE_PENALTY = "EmergencyInactivePenalty"

SIDE_GENESIS_ADDRESS = "GenesisAddress"
SIDE_RECHARGE_ADDRESS = "SideRechargeAddress"
SIDE_WITHDRAW_ADDRESS = "SideWithdrawAddress"

CONFIG_CR_VOTING_START_HEIGHT = "CRVotingStartHeight"
CONFIG_CR_COMMITTEE_START_HEIGHT = "CRCommitteeStartHeight"

MAX_NODE_PER_HOST = "MaxNodePerHost"
CONFIG_CR_CHECK_REWARD_HEIGHT = "CheckRewardHeight"
CONFIG_CR_CONFIGURATION = "CRConfiguration"
CONFIG_MEMBER_COUNT = "MemberCount"
CONFIG_CR_VOTING_PERIOD = "VotingPeriod"
CONFIG_CR_DUTY_PERIOD = "DutyPeriod"
CONFIG_VOTING_PERIOD = "VotingPeriod"
CONFIG_DUTY_PERIOD = "DutyPeriod"
CONFIG_DEPOSIT_LOCKUP_BLOCKS = "DepositLockupBlocks"
CONFIG_CRC_APPROPRIATE_PERCENTAGE = "CRCAppropriatePercentage"
CONFIG_MAX_COMMITTEE_PROPOSAL_COUNT = "MaxCommitteeProposalCount"
CONFIG_MAX_PROPOSAL_TRACKING_COUNT = "MaxProposalTrackingCount"
CONFIG_PROPOSAL_CR_VOTING_PERIOD = "ProposalCRVotingPeriod"
CONFIG_PROPOSAL_PUBLIC_VOTING_PERIOD = "ProposalPublicVotingPeriod"
CONFIG_CR_AGREEMENT_COUNT = "CRAgreementCount"
CONFIG_VOTER_REJECT_PERCENTAGE = "VoterRejectPercentage"
CONFIG_REGISTER_CR_BY_DID_HEIGHT = "RegisterCRByDIDHeight"

TO_SELA = 100000000
